export interface TipoDato {
  TIPOVARIABLE_ID: number;
  DESCRIPCION: string;
  SerialKey: string | null;
  ESTADO: string | null;
  USUARIO_REG: string | null;
  FECHA_REG: string | null;
  USUARIO_ACT: string | null;
  FECHA_ACT: string | null;
  FILTRO: string | null;
  FLG_MASIVO: boolean;
  FLG_MEMORIA: boolean;
  FLG_MODIFICADO: boolean;
  PageSize: number;
  PageNumber: number;
  TotalPage: number;
}

export interface ParametricaCalculo {
  PARAMETRICASCALCULO_ID: number;
  PARAMETRICASCALCULO_IDS: number | null;
  CODIGO: string;
  DESCRIPCION: string;
  TIPODATO_ID: number | null;
  VALOR: string;
  FLG_ESTADO: boolean;
  PARAMETRICASCALCULOKey: string | null;
  TIPODATOKey: string;
  ListaTipoDato: any[] | null;
  TIPODATO: TipoDato;
  SerialKey: string;
  ESTADO: string;
  USUARIO_REG: string;
  FECHA_REG: string;
  USUARIO_ACT: string;
  FECHA_ACT: string | null;
  FILTRO: string | null;
  FLG_MASIVO: boolean;
  FLG_MEMORIA: boolean;
  FLG_MODIFICADO: boolean;
  PageSize: number;
  PageNumber: number;
  TotalPage: number;
}

export const TIPO_DATO_OPTIONS: string[] = [
  'bit',
  'char',
  'date',
  'datetime',
  'decimal',
  'int',
  'nchar',
  'numeric',
  'nvarchar',
  'string',
  'time',
  'TimeSpan',
  'varchar'
];

export const VALORES_GENERALES_MOCK: ParametricaCalculo[] = [
  {
    PARAMETRICASCALCULO_ID: 0,
    PARAMETRICASCALCULO_IDS: null,
    CODIGO: 'CALCPROV',
    DESCRIPCION: 'Cálc. de Provisiones: 1=[Base/30 * Dias], 2=[Sueldo+Asig.Fam * Factor], 3=[GrupoImp * Factor]',
    TIPODATO_ID: null,
    VALOR: '2',
    FLG_ESTADO: true,
    PARAMETRICASCALCULOKey: null,
    TIPODATOKey: 'ZdoUbVSc0Lh-lhlTyBFxgA..',
    ListaTipoDato: null,
    TIPODATO: {
      TIPOVARIABLE_ID: 0,
      DESCRIPCION: 'int',
      SerialKey: null,
      ESTADO: null,
      USUARIO_REG: null,
      FECHA_REG: null,
      USUARIO_ACT: null,
      FECHA_ACT: null,
      FILTRO: null,
      FLG_MASIVO: false,
      FLG_MEMORIA: false,
      FLG_MODIFICADO: false,
      PageSize: 0,
      PageNumber: 0,
      TotalPage: 0
    },
    SerialKey: 'Sq9I0ghtQ9xPgmw25r1R8w..',
    ESTADO: 'A',
    USUARIO_REG: 'sys',
    FECHA_REG: '/Date(1686773409000)/',
    USUARIO_ACT: 'bacuna',
    FECHA_ACT: '/Date(1754949549000)/',
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 68
  },
  {
    PARAMETRICASCALCULO_ID: 0,
    PARAMETRICASCALCULO_IDS: null,
    CODIGO: 'FACTPROVAC',
    DESCRIPCION: 'Factor de Provisiones de Vacaciones',
    TIPODATO_ID: null,
    VALOR: '0.0833',
    FLG_ESTADO: true,
    PARAMETRICASCALCULOKey: null,
    TIPODATOKey: 'AtjPeVHIBDXVnFAEqlS6bg..',
    ListaTipoDato: null,
    TIPODATO: {
      TIPOVARIABLE_ID: 0,
      DESCRIPCION: 'decimal',
      SerialKey: null,
      ESTADO: null,
      USUARIO_REG: null,
      FECHA_REG: null,
      USUARIO_ACT: null,
      FECHA_ACT: null,
      FILTRO: null,
      FLG_MASIVO: false,
      FLG_MEMORIA: false,
      FLG_MODIFICADO: false,
      PageSize: 0,
      PageNumber: 0,
      TotalPage: 0
    },
    SerialKey: 'ZdoUbVSc0Lh-lhlTyBFxgA..',
    ESTADO: 'A',
    USUARIO_REG: 'sys',
    FECHA_REG: '/Date(1686773409000)/',
    USUARIO_ACT: '',
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 68
  },
  {
    PARAMETRICASCALCULO_ID: 0,
    PARAMETRICASCALCULO_IDS: null,
    CODIGO: 'FACTPROGRA',
    DESCRIPCION: 'Factor de Provisiones de Gratificacion',
    TIPODATO_ID: null,
    VALOR: '0.1667',
    FLG_ESTADO: true,
    PARAMETRICASCALCULOKey: null,
    TIPODATOKey: 'AtjPeVHIBDXVnFAEqlS6bg..',
    ListaTipoDato: null,
    TIPODATO: {
      TIPOVARIABLE_ID: 0,
      DESCRIPCION: 'decimal',
      SerialKey: null,
      ESTADO: null,
      USUARIO_REG: null,
      FECHA_REG: null,
      USUARIO_ACT: null,
      FECHA_ACT: null,
      FILTRO: null,
      FLG_MASIVO: false,
      FLG_MEMORIA: false,
      FLG_MODIFICADO: false,
      PageSize: 0,
      PageNumber: 0,
      TotalPage: 0
    },
    SerialKey: '-5MGob6a4qesJ3wWlaQX1w..',
    ESTADO: 'A',
    USUARIO_REG: 'sys',
    FECHA_REG: '/Date(1687301596000)/',
    USUARIO_ACT: '',
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 68
  },
  {
    PARAMETRICASCALCULO_ID: 0,
    PARAMETRICASCALCULO_IDS: null,
    CODIGO: 'FACTPROCTS',
    DESCRIPCION: 'Factor de Provisiones de CTS',
    TIPODATO_ID: null,
    VALOR: '0.0972',
    FLG_ESTADO: true,
    PARAMETRICASCALCULOKey: null,
    TIPODATOKey: 'AtjPeVHIBDXVnFAEqlS6bg..',
    ListaTipoDato: null,
    TIPODATO: {
      TIPOVARIABLE_ID: 0,
      DESCRIPCION: 'decimal',
      SerialKey: null,
      ESTADO: null,
      USUARIO_REG: null,
      FECHA_REG: null,
      USUARIO_ACT: null,
      FECHA_ACT: null,
      FILTRO: null,
      FLG_MASIVO: false,
      FLG_MEMORIA: false,
      FLG_MODIFICADO: false,
      PageSize: 0,
      PageNumber: 0,
      TotalPage: 0
    },
    SerialKey: 'tdSviJfoGlp7C5BkJBSeMQ..',
    ESTADO: 'A',
    USUARIO_REG: 'sys',
    FECHA_REG: '/Date(1687560476000)/',
    USUARIO_ACT: '',
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 68
  },
  {
    PARAMETRICASCALCULO_ID: 0,
    PARAMETRICASCALCULO_IDS: null,
    CODIGO: 'INICIOCCVAC',
    DESCRIPCION: 'Periodo Desde Actualización Cuenta Corriente Vacaciones',
    TIPODATO_ID: null,
    VALOR: '01/10/2025',
    FLG_ESTADO: true,
    PARAMETRICASCALCULOKey: null,
    TIPODATOKey: 'j8ILvvp4aE94oHNVkTGY5A..',
    ListaTipoDato: null,
    TIPODATO: {
      TIPOVARIABLE_ID: 0,
      DESCRIPCION: 'date',
      SerialKey: null,
      ESTADO: null,
      USUARIO_REG: null,
      FECHA_REG: null,
      USUARIO_ACT: null,
      FECHA_ACT: null,
      FILTRO: null,
      FLG_MASIVO: false,
      FLG_MEMORIA: false,
      FLG_MODIFICADO: false,
      PageSize: 0,
      PageNumber: 0,
      TotalPage: 0
    },
    SerialKey: 'j8ILvvp4aE94oHNVkTGY5A..',
    ESTADO: 'A',
    USUARIO_REG: 'wflores',
    FECHA_REG: '/Date(1696977515000)/',
    USUARIO_ACT: 'bacuna',
    FECHA_ACT: '/Date(1763152368000)/',
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 68
  },
  {
    PARAMETRICASCALCULO_ID: 0,
    PARAMETRICASCALCULO_IDS: null,
    CODIGO: 'CALCGRATIT_BASE',
    DESCRIPCION: 'Cálc. Grati Trunca Base: 1=[Meses completos], 2=[Días laborados]',
    TIPODATO_ID: null,
    VALOR: '1',
    FLG_ESTADO: true,
    PARAMETRICASCALCULOKey: null,
    TIPODATOKey: 'ZdoUbVSc0Lh-lhlTyBFxgA..',
    ListaTipoDato: null,
    TIPODATO: {
      TIPOVARIABLE_ID: 0,
      DESCRIPCION: 'int',
      SerialKey: null,
      ESTADO: null,
      USUARIO_REG: null,
      FECHA_REG: null,
      USUARIO_ACT: null,
      FECHA_ACT: null,
      FILTRO: null,
      FLG_MASIVO: false,
      FLG_MEMORIA: false,
      FLG_MODIFICADO: false,
      PageSize: 0,
      PageNumber: 0,
      TotalPage: 0
    },
    SerialKey: 'ckeNgNJtP22tIHmmdz12OA..',
    ESTADO: 'A',
    USUARIO_REG: 'wflores',
    FECHA_REG: '/Date(1707239280000)/',
    USUARIO_ACT: 'sujeyp',
    FECHA_ACT: '/Date(1727807866000)/',
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 68
  },
  {
    PARAMETRICASCALCULO_ID: 0,
    PARAMETRICASCALCULO_IDS: null,
    CODIGO: 'CALCGRATIT_PVAR',
    DESCRIPCION: 'Cálc. Grati Trunca Prom. Variables: 1=[Mes actual], 2=[Mes cerrado]',
    TIPODATO_ID: null,
    VALOR: '1',
    FLG_ESTADO: true,
    PARAMETRICASCALCULOKey: null,
    TIPODATOKey: 'ZdoUbVSc0Lh-lhlTyBFxgA..',
    ListaTipoDato: null,
    TIPODATO: {
      TIPOVARIABLE_ID: 0,
      DESCRIPCION: 'int',
      SerialKey: null,
      ESTADO: null,
      USUARIO_REG: null,
      FECHA_REG: null,
      USUARIO_ACT: null,
      FECHA_ACT: null,
      FILTRO: null,
      FLG_MASIVO: false,
      FLG_MEMORIA: false,
      FLG_MODIFICADO: false,
      PageSize: 0,
      PageNumber: 0,
      TotalPage: 0
    },
    SerialKey: 'nnbQqOFwGpJlRgkUfVlzQg..',
    ESTADO: 'A',
    USUARIO_REG: 'wflores',
    FECHA_REG: '/Date(1707239467000)/',
    USUARIO_ACT: 'wflores',
    FECHA_ACT: '/Date(1707318358000)/',
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 68
  },
  {
    PARAMETRICASCALCULO_ID: 0,
    PARAMETRICASCALCULO_IDS: null,
    CODIGO: 'AJU_CONT',
    DESCRIPCION: 'Ajuste de los Asientos Contables',
    TIPODATO_ID: null,
    VALOR: '0.05',
    FLG_ESTADO: true,
    PARAMETRICASCALCULOKey: null,
    TIPODATOKey: 'AtjPeVHIBDXVnFAEqlS6bg..',
    ListaTipoDato: null,
    TIPODATO: {
      TIPOVARIABLE_ID: 0,
      DESCRIPCION: 'decimal',
      SerialKey: null,
      ESTADO: null,
      USUARIO_REG: null,
      FECHA_REG: null,
      USUARIO_ACT: null,
      FECHA_ACT: null,
      FILTRO: null,
      FLG_MASIVO: false,
      FLG_MEMORIA: false,
      FLG_MODIFICADO: false,
      PageSize: 0,
      PageNumber: 0,
      TotalPage: 0
    },
    SerialKey: 'AtjPeVHIBDXVnFAEqlS6bg..',
    ESTADO: 'A',
    USUARIO_REG: 'mcasapia',
    FECHA_REG: '/Date(1712087868000)/',
    USUARIO_ACT: '',
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 68
  },
  {
    PARAMETRICASCALCULO_ID: 0,
    PARAMETRICASCALCULO_IDS: null,
    CODIGO: 'RMVNOCTURNO',
    DESCRIPCION: 'Porcentaje Remuneración Mínima Vital Nocturna',
    TIPODATO_ID: null,
    VALOR: '35',
    FLG_ESTADO: true,
    PARAMETRICASCALCULOKey: null,
    TIPODATOKey: 'AtjPeVHIBDXVnFAEqlS6bg..',
    ListaTipoDato: null,
    TIPODATO: {
      TIPOVARIABLE_ID: 0,
      DESCRIPCION: 'decimal',
      SerialKey: null,
      ESTADO: null,
      USUARIO_REG: null,
      FECHA_REG: null,
      USUARIO_ACT: null,
      FECHA_ACT: null,
      FILTRO: null,
      FLG_MASIVO: false,
      FLG_MEMORIA: false,
      FLG_MODIFICADO: false,
      PageSize: 0,
      PageNumber: 0,
      TotalPage: 0
    },
    SerialKey: 'nFVPjYzG07YyPQQZHM7cVg..',
    ESTADO: 'A',
    USUARIO_REG: 'wflores',
    FECHA_REG: '/Date(1713282630000)/',
    USUARIO_ACT: '',
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 68
  },
  {
    PARAMETRICASCALCULO_ID: 0,
    PARAMETRICASCALCULO_IDS: null,
    CODIGO: 'HR25LIM',
    DESCRIPCION: 'Límite de horas extras al 25%',
    TIPODATO_ID: null,
    VALOR: '2',
    FLG_ESTADO: true,
    PARAMETRICASCALCULOKey: null,
    TIPODATOKey: 'ZdoUbVSc0Lh-lhlTyBFxgA..',
    ListaTipoDato: null,
    TIPODATO: {
      TIPOVARIABLE_ID: 0,
      DESCRIPCION: 'int',
      SerialKey: null,
      ESTADO: null,
      USUARIO_REG: null,
      FECHA_REG: null,
      USUARIO_ACT: null,
      FECHA_ACT: null,
      FILTRO: null,
      FLG_MASIVO: false,
      FLG_MEMORIA: false,
      FLG_MODIFICADO: false,
      PageSize: 0,
      PageNumber: 0,
      TotalPage: 0
    },
    SerialKey: 'NxXhEbWul1O2jacIam5n8A..',
    ESTADO: 'A',
    USUARIO_REG: 'mcasapia',
    FECHA_REG: '/Date(1713300316000)/',
    USUARIO_ACT: '',
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 68
  },
  {
    PARAMETRICASCALCULO_ID: 0,
    PARAMETRICASCALCULO_IDS: null,
    CODIGO: 'PRIMATEXTIL',
    DESCRIPCION: 'Porcentaje de Prima Textil',
    TIPODATO_ID: null,
    VALOR: '10',
    FLG_ESTADO: true,
    PARAMETRICASCALCULOKey: null,
    TIPODATOKey: 'AtjPeVHIBDXVnFAEqlS6bg..',
    ListaTipoDato: null,
    TIPODATO: {
      TIPOVARIABLE_ID: 0,
      DESCRIPCION: 'decimal',
      SerialKey: null,
      ESTADO: null,
      USUARIO_REG: null,
      FECHA_REG: null,
      USUARIO_ACT: null,
      FECHA_ACT: null,
      FILTRO: null,
      FLG_MASIVO: false,
      FLG_MEMORIA: false,
      FLG_MODIFICADO: false,
      PageSize: 0,
      PageNumber: 0,
      TotalPage: 0
    },
    SerialKey: 'CfAspb3jkPhAMWq05atFOw..',
    ESTADO: 'A',
    USUARIO_REG: 'wflores',
    FECHA_REG: '/Date(1713384634000)/',
    USUARIO_ACT: 'fhooker',
    FECHA_ACT: '/Date(1719866714000)/',
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 68
  },
  {
    PARAMETRICASCALCULO_ID: 0,
    PARAMETRICASCALCULO_IDS: null,
    CODIGO: 'CTST_SEXTGRATI',
    DESCRIPCION: 'Cálc. CTS Trunca 6to Grati: 1=[Periodo CTS] 2=[Última gratificación pagada]',
    TIPODATO_ID: null,
    VALOR: '1',
    FLG_ESTADO: true,
    PARAMETRICASCALCULOKey: null,
    TIPODATOKey: 'ZdoUbVSc0Lh-lhlTyBFxgA..',
    ListaTipoDato: null,
    TIPODATO: {
      TIPOVARIABLE_ID: 0,
      DESCRIPCION: 'int',
      SerialKey: null,
      ESTADO: null,
      USUARIO_REG: null,
      FECHA_REG: null,
      USUARIO_ACT: null,
      FECHA_ACT: null,
      FILTRO: null,
      FLG_MASIVO: false,
      FLG_MEMORIA: false,
      FLG_MODIFICADO: false,
      PageSize: 0,
      PageNumber: 0,
      TotalPage: 0
    },
    SerialKey: 'erSaAST56biEcxZ2brDOiw..',
    ESTADO: 'A',
    USUARIO_REG: 'wflores',
    FECHA_REG: '/Date(1716582998000)/',
    USUARIO_ACT: 'sujeyp',
    FECHA_ACT: '/Date(1716589466000)/',
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 68
  },
  {
    PARAMETRICASCALCULO_ID: 0,
    PARAMETRICASCALCULO_IDS: null,
    CODIGO: 'CALCGRATI_BASE',
    DESCRIPCION: 'Cálc. Grati Base: 1=[Meses completos], 2=[Días laborados]',
    TIPODATO_ID: null,
    VALOR: '1',
    FLG_ESTADO: true,
    PARAMETRICASCALCULOKey: null,
    TIPODATOKey: 'ZdoUbVSc0Lh-lhlTyBFxgA..',
    ListaTipoDato: null,
    TIPODATO: {
      TIPOVARIABLE_ID: 0,
      DESCRIPCION: 'int',
      SerialKey: null,
      ESTADO: null,
      USUARIO_REG: null,
      FECHA_REG: null,
      USUARIO_ACT: null,
      FECHA_ACT: null,
      FILTRO: null,
      FLG_MASIVO: false,
      FLG_MEMORIA: false,
      FLG_MODIFICADO: false,
      PageSize: 0,
      PageNumber: 0,
      TotalPage: 0
    },
    SerialKey: '68-7QiHpoXuI9YDaUwJL7w..',
    ESTADO: 'A',
    USUARIO_REG: 'mcasapia',
    FECHA_REG: '/Date(1720103230000)/',
    USUARIO_ACT: 'sujeyp',
    FECHA_ACT: '/Date(1730907377000)/',
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 68
  },
  {
    PARAMETRICASCALCULO_ID: 0,
    PARAMETRICASCALCULO_IDS: null,
    CODIGO: 'CALCCTS',
    DESCRIPCION: 'Cálc. CTS: 1=[Por periodo], 2=[Por días]',
    TIPODATO_ID: null,
    VALOR: '2',
    FLG_ESTADO: true,
    PARAMETRICASCALCULOKey: null,
    TIPODATOKey: 'ZdoUbVSc0Lh-lhlTyBFxgA..',
    ListaTipoDato: null,
    TIPODATO: {
      TIPOVARIABLE_ID: 0,
      DESCRIPCION: 'int',
      SerialKey: null,
      ESTADO: null,
      USUARIO_REG: null,
      FECHA_REG: null,
      USUARIO_ACT: null,
      FECHA_ACT: null,
      FILTRO: null,
      FLG_MASIVO: false,
      FLG_MEMORIA: false,
      FLG_MODIFICADO: false,
      PageSize: 0,
      PageNumber: 0,
      TotalPage: 0
    },
    SerialKey: 'Pu2DwIJR5IzNIlav1P5oVg..',
    ESTADO: 'A',
    USUARIO_REG: 'wflores',
    FECHA_REG: '/Date(1721082348000)/',
    USUARIO_ACT: 'sujeyp',
    FECHA_ACT: '/Date(1731537997000)/',
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 68
  },
  {
    PARAMETRICASCALCULO_ID: 0,
    PARAMETRICASCALCULO_IDS: null,
    CODIGO: 'CALCBASE_VAR',
    DESCRIPCION: 'Cálc. División Base Variable: 1=[Entre meses], 2=[Entre días] ',
    TIPODATO_ID: null,
    VALOR: '1',
    FLG_ESTADO: true,
    PARAMETRICASCALCULOKey: null,
    TIPODATOKey: 'ZdoUbVSc0Lh-lhlTyBFxgA..',
    ListaTipoDato: null,
    TIPODATO: {
      TIPOVARIABLE_ID: 0,
      DESCRIPCION: 'int',
      SerialKey: null,
      ESTADO: null,
      USUARIO_REG: null,
      FECHA_REG: null,
      USUARIO_ACT: null,
      FECHA_ACT: null,
      FILTRO: null,
      FLG_MASIVO: false,
      FLG_MEMORIA: false,
      FLG_MODIFICADO: false,
      PageSize: 0,
      PageNumber: 0,
      TotalPage: 0
    },
    SerialKey: '3J8uFGLdQ1gYFN6R21CKCA..',
    ESTADO: 'A',
    USUARIO_REG: 'wflores',
    FECHA_REG: '/Date(1721853670000)/',
    USUARIO_ACT: '',
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 68
  }
];
