export interface PeriodoRecord {
  PERIODO_ID: number;
  DESCRIPCION: string;
  PERIODO_DESDE: string;
  PERIODO_HASTA: string;
  PERIODOS_ID: number | null;
  ListaPeriodos: any[] | null;
  ListaPeriodosAnios: any[] | null;
  AGRUPADOR: string | null;
  ANOS: number | null;
  PERIODODETALLE_IDS: any[] | null;
  SerialKey: string;
  ESTADO: string;
  USUARIO_REG: string;
  FECHA_REG: string;
  USUARIO_ACT: string;
  FECHA_ACT: string | null;
  FILTRO: string | null;
  FLG_MASIVO: boolean;
  FLG_MEMORIA: boolean;
  FLG_MODIFICADO: boolean;
  PageSize: number;
  PageNumber: number;
  TotalPage: number;
}

export const PERIODOS_MOCK: PeriodoRecord[] = [
  {
    PERIODO_ID: 0,
    DESCRIPCION: "12/2030",
    PERIODO_DESDE: "/Date(1922331600000)/",
    PERIODO_HASTA: "/Date(1924923600000)/",
    PERIODOS_ID: null,
    ListaPeriodos: null,
    ListaPeriodosAnios: null,
    AGRUPADOR: null,
    ANOS: null,
    PERIODODETALLE_IDS: null,
    SerialKey: "vjw4C7YQtWlPT34Bh4_9zg..",
    ESTADO: "A",
    USUARIO_REG: "sys",
    FECHA_REG: "/Date(1635351226000)/",
    USUARIO_ACT: "",
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 372
  },
  {
    PERIODO_ID: 0,
    DESCRIPCION: "11/2030",
    PERIODO_DESDE: "/Date(1919739600000)/",
    PERIODO_HASTA: "/Date(1922245200000)/",
    PERIODOS_ID: null,
    ListaPeriodos: null,
    ListaPeriodosAnios: null,
    AGRUPADOR: null,
    ANOS: null,
    PERIODODETALLE_IDS: null,
    SerialKey: "0rWPUXVtO0gRNA81C_O6Fw..",
    ESTADO: "A",
    USUARIO_REG: "sys",
    FECHA_REG: "/Date(1635351226000)/",
    USUARIO_ACT: "",
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 372
  },
  {
    PERIODO_ID: 0,
    DESCRIPCION: "10/2030",
    PERIODO_DESDE: "/Date(1917061200000)/",
    PERIODO_HASTA: "/Date(1919653200000)/",
    PERIODOS_ID: null,
    ListaPeriodos: null,
    ListaPeriodosAnios: null,
    AGRUPADOR: null,
    ANOS: null,
    PERIODODETALLE_IDS: null,
    SerialKey: "4TquyKVCvc3YuuZf48xKgw..",
    ESTADO: "A",
    USUARIO_REG: "sys",
    FECHA_REG: "/Date(1635351226000)/",
    USUARIO_ACT: "",
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 372
  },
  {
    PERIODO_ID: 0,
    DESCRIPCION: "09/2030",
    PERIODO_DESDE: "/Date(1914469200000)/",
    PERIODO_HASTA: "/Date(1916974800000)/",
    PERIODOS_ID: null,
    ListaPeriodos: null,
    ListaPeriodosAnios: null,
    AGRUPADOR: null,
    ANOS: null,
    PERIODODETALLE_IDS: null,
    SerialKey: "1qBZG5txvQQA2Ehz15d2Rg..",
    ESTADO: "A",
    USUARIO_REG: "sys",
    FECHA_REG: "/Date(1635351226000)/",
    USUARIO_ACT: "",
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 372
  },
  {
    PERIODO_ID: 0,
    DESCRIPCION: "08/2030",
    PERIODO_DESDE: "/Date(1911790800000)/",
    PERIODO_HASTA: "/Date(1914382800000)/",
    PERIODOS_ID: null,
    ListaPeriodos: null,
    ListaPeriodosAnios: null,
    AGRUPADOR: null,
    ANOS: null,
    PERIODODETALLE_IDS: null,
    SerialKey: "rtzRSFk-o5MLEldTnHlIWA..",
    ESTADO: "A",
    USUARIO_REG: "sys",
    FECHA_REG: "/Date(1635351226000)/",
    USUARIO_ACT: "",
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 372
  },
  {
    PERIODO_ID: 0,
    DESCRIPCION: "07/2030",
    PERIODO_DESDE: "/Date(1909112400000)/",
    PERIODO_HASTA: "/Date(1911704400000)/",
    PERIODOS_ID: null,
    ListaPeriodos: null,
    ListaPeriodosAnios: null,
    AGRUPADOR: null,
    ANOS: null,
    PERIODODETALLE_IDS: null,
    SerialKey: "B46RtiIjfPApddkU2z7mJg..",
    ESTADO: "A",
    USUARIO_REG: "sys",
    FECHA_REG: "/Date(1635351226000)/",
    USUARIO_ACT: "",
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 372
  },
  {
    PERIODO_ID: 0,
    DESCRIPCION: "06/2030",
    PERIODO_DESDE: "/Date(1906520400000)/",
    PERIODO_HASTA: "/Date(1909026000000)/",
    PERIODOS_ID: null,
    ListaPeriodos: null,
    ListaPeriodosAnios: null,
    AGRUPADOR: null,
    ANOS: null,
    PERIODODETALLE_IDS: null,
    SerialKey: "iIL78Gn9ySYJW2sH4nF4HQ..",
    ESTADO: "A",
    USUARIO_REG: "sys",
    FECHA_REG: "/Date(1635351226000)/",
    USUARIO_ACT: "",
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 372
  },
  {
    PERIODO_ID: 0,
    DESCRIPCION: "05/2030",
    PERIODO_DESDE: "/Date(1903842000000)/",
    PERIODO_HASTA: "/Date(1906434000000)/",
    PERIODOS_ID: null,
    ListaPeriodos: null,
    ListaPeriodosAnios: null,
    AGRUPADOR: null,
    ANOS: null,
    PERIODODETALLE_IDS: null,
    SerialKey: "b5De7Sbiq2w1--OJK2-J5w..",
    ESTADO: "A",
    USUARIO_REG: "sys",
    FECHA_REG: "/Date(1635351226000)/",
    USUARIO_ACT: "",
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 372
  },
  {
    PERIODO_ID: 0,
    DESCRIPCION: "04/2030",
    PERIODO_DESDE: "/Date(1901250000000)/",
    PERIODO_HASTA: "/Date(1903755600000)/",
    PERIODOS_ID: null,
    ListaPeriodos: null,
    ListaPeriodosAnios: null,
    AGRUPADOR: null,
    ANOS: null,
    PERIODODETALLE_IDS: null,
    SerialKey: "5F9-M8Iwk8N3RpQaPF9yig..",
    ESTADO: "A",
    USUARIO_REG: "sys",
    FECHA_REG: "/Date(1635351226000)/",
    USUARIO_ACT: "",
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 372
  },
  {
    PERIODO_ID: 0,
    DESCRIPCION: "03/2030",
    PERIODO_DESDE: "/Date(1898571600000)/",
    PERIODO_HASTA: "/Date(1901163600000)/",
    PERIODOS_ID: null,
    ListaPeriodos: null,
    ListaPeriodosAnios: null,
    AGRUPADOR: null,
    ANOS: null,
    PERIODODETALLE_IDS: null,
    SerialKey: "UWZpQeMgEg5TtRzDHOEGyQ..",
    ESTADO: "A",
    USUARIO_REG: "sys",
    FECHA_REG: "/Date(1635351226000)/",
    USUARIO_ACT: "",
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 372
  },
  {
    PERIODO_ID: 0,
    DESCRIPCION: "02/2030",
    PERIODO_DESDE: "/Date(1896152400000)/",
    PERIODO_HASTA: "/Date(1898485200000)/",
    PERIODOS_ID: null,
    ListaPeriodos: null,
    ListaPeriodosAnios: null,
    AGRUPADOR: null,
    ANOS: null,
    PERIODODETALLE_IDS: null,
    SerialKey: "wcITuKv1lIOal26o8dSDhA..",
    ESTADO: "A",
    USUARIO_REG: "sys",
    FECHA_REG: "/Date(1635351226000)/",
    USUARIO_ACT: "",
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 372
  },
  {
    PERIODO_ID: 0,
    DESCRIPCION: "01/2030",
    PERIODO_DESDE: "/Date(1893474000000)/",
    PERIODO_HASTA: "/Date(1896066000000)/",
    PERIODOS_ID: null,
    ListaPeriodos: null,
    ListaPeriodosAnios: null,
    AGRUPADOR: null,
    ANOS: null,
    PERIODODETALLE_IDS: null,
    SerialKey: "2fydHsP00Ujz4o3yDVcs7A..",
    ESTADO: "A",
    USUARIO_REG: "sys",
    FECHA_REG: "/Date(1635351226000)/",
    USUARIO_ACT: "",
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 372
  },
  {
    PERIODO_ID: 0,
    DESCRIPCION: "12/2029",
    PERIODO_DESDE: "/Date(1890795600000)/",
    PERIODO_HASTA: "/Date(1893387600000)/",
    PERIODOS_ID: null,
    ListaPeriodos: null,
    ListaPeriodosAnios: null,
    AGRUPADOR: null,
    ANOS: null,
    PERIODODETALLE_IDS: null,
    SerialKey: "pg2tUpROlbO0F5CUeTxhIQ..",
    ESTADO: "A",
    USUARIO_REG: "sys",
    FECHA_REG: "/Date(1635351226000)/",
    USUARIO_ACT: "",
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 372
  },
  {
    PERIODO_ID: 0,
    DESCRIPCION: "11/2029",
    PERIODO_DESDE: "/Date(1888203600000)/",
    PERIODO_HASTA: "/Date(1890709200000)/",
    PERIODOS_ID: null,
    ListaPeriodos: null,
    ListaPeriodosAnios: null,
    AGRUPADOR: null,
    ANOS: null,
    PERIODODETALLE_IDS: null,
    SerialKey: "b5hdqLvvpCktOmKr80B8vg..",
    ESTADO: "A",
    USUARIO_REG: "sys",
    FECHA_REG: "/Date(1635351226000)/",
    USUARIO_ACT: "",
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 372
  },
  {
    PERIODO_ID: 0,
    DESCRIPCION: "10/2029",
    PERIODO_DESDE: "/Date(1885525200000)/",
    PERIODO_HASTA: "/Date(1888117200000)/",
    PERIODOS_ID: null,
    ListaPeriodos: null,
    ListaPeriodosAnios: null,
    AGRUPADOR: null,
    ANOS: null,
    PERIODODETALLE_IDS: null,
    SerialKey: "kJBMkOMIdS81aK5a6UUDBw..",
    ESTADO: "A",
    USUARIO_REG: "sys",
    FECHA_REG: "/Date(1635351226000)/",
    USUARIO_ACT: "",
    FECHA_ACT: null,
    FILTRO: null,
    FLG_MASIVO: false,
    FLG_MEMORIA: false,
    FLG_MODIFICADO: false,
    PageSize: 0,
    PageNumber: 0,
    TotalPage: 372
  }
];
